apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasktracker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasktracker
  template:
    metadata:
      labels:
        app: tasktracker
    spec:
      containers:
        - name: app
          image: tasktracker:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db-service:5432/tasktracker
            - name: SPRING_DATASOURCE_USERNAME
              value: user
            - name: SPRING_DATASOURCE_PASSWORD
              value: password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: tasktracker
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  ports:
    - port: 5433
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: tasktracker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
