apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasktracker-deployment
  labels:
    app: tasktracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasktracker
  template:
    metadata:
      labels:
        app: tasktracker
    spec:
      containers:
        - name: tasktracker
          image: tasktracker:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: "jdbc:postgresql://localhost:5433/task-tracker"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: tasktracker-service
spec:
  selector:
    app: tasktracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
