
services:
  db:
    image: postgres:16.4
    environment:
      POSTGRES_DB: task-tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/task-tracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 111
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
